### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by cjsb** [marcos-sandim/boundary-detection#1]
Oi,

eu tentei rodar o código mas deu error de função depricated. Em qual versão do python foi feito o código e tem algum setup pra rodar o código?

Obrigado

**Comment by cjsb** [comment]
Sendo mais preciso, o erro é esse:  DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

**Comment by marianyfs** [comment]
Você pode dizer qual def () gerou o problema? Já resolveu?

**Comment by marcos-sandim** [comment]
Olá,

Me desculpem pela demora em responder.

De qualquer forma, 5 meses depois o problema está resolvido.

Não lembro qual versao do python e das bibliotecas que usei pra desenvolver, mas resolvi agora usando Python 2.7.9 e scikit-learn 0.18.1. O warning não deve mais aparecer.

Não há um setup pra rodar o codigo, só é necessário ter: numpy, scikit-learn e scipy.
